name: Build and Push Docker Image

on:
  push:
    branches: [main] # 如使用其他分支，请修改这里

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # 关键：允许推送到 ghcr.io

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          # 自动创建仓库路径 ghcr.io/taodev/mycert:latest

      - name: Show Image Info
        run: echo "Pushed ghcr.io/${{ github.repository }}:latest"
      
      - name: Show Info
        run: echo `github.repository ${{ github.repository }}`
